image: node:10

definitions:
  steps:
    - step: &secure
        name: 'Audit and Secure'
        script:
          - npm ci
          - npm run lint
          - npm run secure

pipelines:
  branches:
    master:
      - step: *secure
      - step:
          name: 'Build and Publish'
          script:
            - npm ci
            - npm run build

            # Publish package
            - npm publish --access=public

    feature/*:
      - step: *secure
      - step:
          name: 'Build'
          script:
            - npm ci
            - npm run build

